apiVersion: v1
kind: Service
metadata:
  name: kube-sage-manager
  namespace: kubesage
  labels:
    app: kube-sage-manager
spec:
  type: ClusterIP
  selector:
    app: kube-sage-manager
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
